### Passo 01: Importando as bilbiotecas





In [ ]:
!pip install numpy==1.26.4

In [ ]:
import bs4 as bs
import urllib.request
import re
import nltk
import numpy as np
import random
import string

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
!pip install spacy

In [ ]:
import spacy

In [ ]:
import spacy.cli
spacy.cli.download("pt_core_news_sm")

✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


### Passo 02: Coleta dos dados

In [ ]:
nlp = spacy.load('pt_core_news_sm')

In [ ]:
import urllib.request
from bs4 import BeautifulSoup as bs

def indexarDados(urls):
    conteudo_completo = ""

    for url in urls:
        try:
            link = urllib.request.urlopen(url)
            conteudo = link.read()
            conteudo_html = bs(conteudo, 'lxml')


            paragrafos = conteudo_html.find_all('p')
            conteudo = ''

            for p in paragrafos:
                conteudo += p.text + "\n"

            conteudo_completo += conteudo + "\n\n"
        except Exception as e:
            print(f"Erro ao acessar a URL {url}: {e}")

    return conteudo_completo


urls = [
        'https://pt.wikipedia.org/wiki/Cora%C3%A7%C3%A3o',
        'https://pt.wikipedia.org/wiki/Sistema_circulat%C3%B3rio',
        'https://pt.wikipedia.org/wiki/Cora%C3%A7%C3%A3o_artificial',
        'https://pt.wikipedia.org/wiki/Transplante_de_cora%C3%A7%C3%A3o'

]

conteudo_combined = indexarDados(urls)

print(conteudo_combined)

O coração é um órgão muscular presente nos humanos e em outros animais que bombeia o sangue através dos vasos sanguíneos do sistema circulatório.[1] O sangue fornece ao corpo oxigénio e nutrientes e ajuda a eliminar resíduos metabólicos.[2] Nos humanos, o coração situa-se na cavidade torácica entre os pulmões, num espaço denominado mediastino.[3]

O coração humano divide-se em quatro cavidades. Na parte superior situam-se as aurículas direita e esquerda e, na parte inferior, os ventrículos direito e esquerdo.[4][5] É comum designar o conjunto da aurícula e do ventrículo direitos por "coração direito" e o conjunto equivalente do lado esquerdo por "coração esquerdo".[6] Num coração saudável, as válvulas cardíacas fazem com que o sangue dentro do coração flua em sentido único, impedindo o seu refluxo.[3] O coração é envolvido pelo pericárdio, uma membrana protetora em forma de saco que contém uma pequena quantidade de líquido. A parede do coração é constituída por três camadas: o epicárdi

In [ ]:
conteudo = conteudo_combined.lower()
conteudo

'o coração é um órgão muscular presente nos humanos e em outros animais que bombeia o sangue através dos vasos sanguíneos do sistema circulatório.[1] o sangue fornece ao corpo oxigénio e nutrientes e ajuda a eliminar resíduos metabólicos.[2] nos humanos, o coração situa-se na cavidade torácica entre os pulmões, num espaço denominado mediastino.[3]\n\no coração humano divide-se em quatro cavidades. na parte superior situam-se as aurículas direita e esquerda e, na parte inferior, os ventrículos direito e esquerdo.[4][5] é comum designar o conjunto da aurícula e do ventrículo direitos por "coração direito" e o conjunto equivalente do lado esquerdo por "coração esquerdo".[6] num coração saudável, as válvulas cardíacas fazem com que o sangue dentro do coração flua em sentido único, impedindo o seu refluxo.[3] o coração é envolvido pelo pericárdio, uma membrana protetora em forma de saco que contém uma pequena quantidade de líquido. a parede do coração é constituída por três camadas: o epicá

In [ ]:
lista_sentencas = nltk.sent_tokenize(conteudo)

In [ ]:
lista_sentencas

['o coração é um órgão muscular presente nos humanos e em outros animais que bombeia o sangue através dos vasos sanguíneos do sistema circulatório.',
 '[1] o sangue fornece ao corpo oxigénio e nutrientes e ajuda a eliminar resíduos metabólicos.',
 '[2] nos humanos, o coração situa-se na cavidade torácica entre os pulmões, num espaço denominado mediastino.',
 '[3]\n\no coração humano divide-se em quatro cavidades.',
 'na parte superior situam-se as aurículas direita e esquerda e, na parte inferior, os ventrículos direito e esquerdo.',
 '[4][5] é comum designar o conjunto da aurícula e do ventrículo direitos por "coração direito" e o conjunto equivalente do lado esquerdo por "coração esquerdo".',
 '[6] num coração saudável, as válvulas cardíacas fazem com que o sangue dentro do coração flua em sentido único, impedindo o seu refluxo.',
 '[3] o coração é envolvido pelo pericárdio, uma membrana protetora em forma de saco que contém uma pequena quantidade de líquido.',
 'a parede do coração 

In [ ]:
!python -m spacy download pt_core_news_sm
import spacy

  Using cached https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.7.0/pt_core_news_sm-3.7.0-py3-none-any.whl (13.0 MB)
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
pln = spacy.load("pt_core_news_sm")
pln

### Passo 03: Eliminar palavras sem sentido

In [ ]:
stop_words = spacy.lang.pt.stop_words.STOP_WORDS

In [ ]:
stop_words

{'a',
 'acerca',
 'ademais',
 'adeus',
 'agora',
 'ainda',
 'algo',
 'algumas',
 'alguns',
 'ali',
 'além',
 'ambas',
 'ambos',
 'antes',
 'ao',
 'aos',
 'apenas',
 'apoia',
 'apoio',
 'apontar',
 'após',
 'aquela',
 'aquelas',
 'aquele',
 'aqueles',
 'aqui',
 'aquilo',
 'as',
 'assim',
 'através',
 'atrás',
 'até',
 'aí',
 'baixo',
 'bastante',
 'bem',
 'boa',
 'bom',
 'breve',
 'cada',
 'caminho',
 'catorze',
 'cedo',
 'cento',
 'certamente',
 'certeza',
 'cima',
 'cinco',
 'coisa',
 'com',
 'como',
 'comprida',
 'comprido',
 'conhecida',
 'conhecido',
 'conselho',
 'contra',
 'contudo',
 'corrente',
 'cuja',
 'cujo',
 'custa',
 'cá',
 'da',
 'daquela',
 'daquele',
 'dar',
 'das',
 'de',
 'debaixo',
 'demais',
 'dentro',
 'depois',
 'des',
 'desde',
 'dessa',
 'desse',
 'desta',
 'deste',
 'deve',
 'devem',
 'deverá',
 'dez',
 'dezanove',
 'dezasseis',
 'dezassete',
 'dezoito',
 'diante',
 'direita',
 'disso',
 'diz',
 'dizem',
 'dizer',
 'do',
 'dois',
 'dos',
 'doze',
 'duas',
 'dá

In [ ]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

### Passo 04: Etapa de Pré-processamento

In [ ]:
def preprocessamento(texto):
  texto = re.sub(r"https?://[A-Za-z0-9./]+", ' ', texto)
  documento = pln(texto)
  lista = []
  for token in documento:
    lista.append(token.lemma_)
  lista = [palavra for palavra in lista if palavra not in stop_words and palavra not in string.punctuation]
  lista = ' '.join([str(elemento) for elemento in lista if not elemento.isdigit()])
  return lista

In [ ]:
lista_sentencas_preprocessada = []
for i in range(len(lista_sentencas)):
  lista_sentencas_preprocessada.append(preprocessamento(lista_sentencas[i]))

In [ ]:
lista_sentencas_preprocessada

['coração órgão muscular presente em o humano outro animal bombeiar sangue de o vaso sanguíneo de o circulatório',
 'sangue fornecer a o corpo oxigénio nutriente ajudar eliminar resíduo metabólico',
 'em o humano coração situar se em o cavidade torácico pulmão em um espaço denominar mediastino',
 '\n\n coração humano divider se cavidade',
 'em o alto situam-se aurícula esquerdo em o inferior ventrículo direito esquerdo',
 '4][5 comum designar conjunto de o aurícula de o ventrículo direito coração direito conjunto equivalente de o esquerdo coração esquerdo',
 'em um coração saudável válvula cardíaco sangue de o coração flua sentido único impedir refluxo',
 'coração envolver por o pericárdio membrano protetora saco contémr pequeno quantidade líquido',
 'parede de o coração constituir camada epicárdio miocárdio endocárdio',
 'coração de o restante mamífero de o ave apresentar igualmente cavidade',
 'coração de o peixe apresentar cavidade aurícula ventrículo de o réptel apresentar cavidade

In [ ]:
for _ in range(5):
  i = random.randint(0, len(lista_sentencas) - 1)
  print(lista_sentencas[i])
  print(lista_sentencas_preprocessada[i])
  print('-----')

em muitos casos pode ser necessário um coagulograma para determinar a dose correta de anticoagulantes.
caso necessário coagulograma determinar dose correto anticoagulante
-----
todos os 12 pacientes que receberam o abiocor foram selecionados pela u.s. food and drugs administration (f.d.a.
paciente receber abiocor selecionar por o u.s food and drugs administration f.d.a
-----
os níveis de colesterol podem ser diminuídos com estatinas.
colesterol   diminuír estatina
-----
quando os ventrículos se contraem durante a sístole, as aurículas estão relaxadas e a receber sangue.
ventrículo contrair durante sístole aurícula relaxado receber sangue
-----
[79][82] as propostas de galeno só seriam questionadas cerca de um milénio mais tarde.
79][82 proposta galeno questionar cerca milénio
-----


In [ ]:
textos_boas_vindas_entrada = ('hey', 'olá', 'opa', 'oi', 'eae', 'salve')
textos_boas_vindas_respostas = ('olá me faça uma pergunta de coração ❤️', 'Bora conversar sobre ❤️?', 'O que você manda ❤️?', 'pergunta ai sobre coração ❤️')

In [ ]:
textos_despedidas_entrada = ('tchau', 'adeus', 'até mais', 'até logo', 'falou', 'até breve')
textos_despedidas_respostas = ('Até mais! Qualquer coisa estou aqui', 'Até mais colega!', 'Espero que tenha aproveitado a experiência!', 'Até breve, valeu!')

In [ ]:
'ola tudo bem como vai'.split()

['ola', 'tudo', 'bem', 'como', 'vai']

In [ ]:
def responder_saudacao(texto):
  for palavra in texto.split():
    if palavra.lower() in textos_boas_vindas_entrada:
      return random.choice(textos_boas_vindas_respostas)

In [ ]:
def responder_despedida(texto):
  for palavra in texto.split():
    if palavra.lower() in textos_despedidas_entrada:
      return random.choice(textos_despedidas_respostas)

In [ ]:
responder_despedida('falou')

'Espero que tenha aproveitado a experiência!'

In [ ]:
responder_saudacao('oi tudo bem como vai')

'O que você manda ❤️?'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
frases_teste = lista_sentencas_preprocessada
frases_teste

['coração órgão muscular presente em o humano outro animal bombeiar sangue de o vaso sanguíneo de o circulatório',
 'sangue fornecer a o corpo oxigénio nutriente ajudar eliminar resíduo metabólico',
 'em o humano coração situar se em o cavidade torácico pulmão em um espaço denominar mediastino',
 '\n\n coração humano divider se cavidade',
 'em o alto situam-se aurícula esquerdo em o inferior ventrículo direito esquerdo',
 '4][5 comum designar conjunto de o aurícula de o ventrículo direito coração direito conjunto equivalente de o esquerdo coração esquerdo',
 'em um coração saudável válvula cardíaco sangue de o coração flua sentido único impedir refluxo',
 'coração envolver por o pericárdio membrano protetora saco contémr pequeno quantidade líquido',
 'parede de o coração constituir camada epicárdio miocárdio endocárdio',
 'coração de o restante mamífero de o ave apresentar igualmente cavidade',
 'coração de o peixe apresentar cavidade aurícula ventrículo de o réptel apresentar cavidade

In [ ]:
vetores_palavras = TfidfVectorizer()
palavras_vetorizadas = vetores_palavras.fit_transform(frases_teste)

### Passo 05: Calcular

In [ ]:
type(palavras_vetorizadas)

scipy.sparse._csr.csr_matrix

In [ ]:
palavras_vetorizadas

<661x1850 sparse matrix of type '<class 'numpy.float64'>'
	with 7321 stored elements in Compressed Sparse Row format>

In [ ]:
!pip install --upgrade scikit-learn

print(vetores_palavras.get_feature_names_out())

['105' '106' '11' ... 'órgão' 'único' 'úrico']


In [ ]:
print(vetores_palavras.vocabulary_)

{'coração': 490, 'órgão': 1847, 'muscular': 1196, 'presente': 1384, 'em': 703, 'humano': 960, 'outro': 1277, 'animal': 152, 'bombeiar': 299, 'sangue': 1573, 'de': 534, 'vaso': 1787, 'sanguíneo': 1576, 'circulatório': 380, 'fornecer': 887, 'corpo': 495, 'oxigénio': 1287, 'nutriente': 1240, 'ajudar': 107, 'eliminar': 699, 'resíduo': 1543, 'metabólico': 1153, 'situar': 1639, 'se': 1583, 'cavidade': 348, 'torácico': 1722, 'pulmão': 1432, 'um': 1768, 'espaço': 755, 'denominar': 554, 'mediastino': 1139, 'divider': 645, 'alto': 121, 'situam': 1638, 'aurícula': 233, 'esquerdo': 772, 'inferior': 997, 'ventrículo': 1796, 'direito': 622, 'comum': 435, 'designar': 580, 'conjunto': 453, 'equivalente': 745, 'saudável': 1580, 'válvula': 1821, 'cardíaco': 337, 'flua': 876, 'sentido': 1601, 'único': 1848, 'impedir': 975, 'refluxo': 1481, 'envolver': 733, 'por': 1360, 'pericárdio': 1331, 'membrano': 1149, 'protetora': 1419, 'saco': 1569, 'contémr': 485, 'pequeno': 1320, 'quantidade': 1441, 'líquido': 11

In [ ]:
print(vetores_palavras.idf_)

[6.39665327 6.80211838 6.80211838 ... 4.45074312 5.41582401 6.80211838]


In [ ]:
palavras_vetorizadas.todense()

matrix([[0.        , 0.        , 0.        , ..., 0.28775814, 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]])

### Passo 06: Similaridade Cosseno

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similaridade = cosine_similarity(palavras_vetorizadas[0], palavras_vetorizadas)

In [ ]:
similaridade

array([[1.        , 0.02554417, 0.15376032, 0.18204588, 0.04073501,
        0.07509668, 0.091763  , 0.01540474, 0.04633352, 0.0722235 ,
        0.06299392, 0.05955482, 0.03291914, 0.08371301, 0.04804519,
        0.05432918, 0.02092396, 0.02964328, 0.02217316, 0.0174511 ,
        0.04515552, 0.0187518 , 0.06790442, 0.04663011, 0.30555823,
        0.10317886, 0.21860464, 0.06122477, 0.11321733, 0.05870324,
        0.05079518, 0.10310219, 0.05616692, 0.02110042, 0.0565364 ,
        0.04327939, 0.04299834, 0.05408857, 0.01826074, 0.02442869,
        0.1244882 , 0.        , 0.02285076, 0.15398463, 0.0679006 ,
        0.07103765, 0.04083242, 0.0253062 , 0.02236316, 0.06614708,
        0.07366582, 0.07002136, 0.02785354, 0.04633352, 0.        ,
        0.06222911, 0.        , 0.03315947, 0.06013733, 0.07407477,
        0.09592014, 0.06081608, 0.17068555, 0.01313675, 0.        ,
        0.03196694, 0.139283  , 0.1771842 , 0.04307787, 0.0662669 ,
        0.15812417, 0.        , 0.        , 0.18

In [ ]:
similaridade.argsort()

array([[660, 631, 299, 152, 153, 154, 155, 619, 115, 618,  72,  71, 306,
        648, 293, 649, 292, 164,  64, 346, 651, 165, 629, 436, 347, 297,
         83, 309, 230, 343, 337, 336, 107, 325, 324, 104, 103, 102, 101,
        100,  99, 625, 323, 624,  95, 320,  93,  92, 138, 319, 317, 387,
        313, 390, 168, 345,  56,  54, 204, 582, 351, 257, 636, 251, 247,
        510, 211, 243, 214, 583, 574, 242, 241, 240, 218, 239, 544, 237,
        235, 559, 234, 233, 569, 290, 203, 259, 451, 604, 634, 174, 603,
        175, 281, 642, 600, 280, 187, 202, 276, 468, 356, 191, 272, 193,
        269, 267, 264, 262, 490, 585, 496,  41, 113, 334, 434, 189, 580,
        156,  63, 348, 166, 399, 626, 623, 630, 558, 541, 609, 498, 176,
        363, 449, 287, 359, 181, 400,   7, 179, 255, 167, 577, 177, 578,
        588, 427, 425, 401, 169, 171, 563, 567,  74,  90,  78, 291,  19,
        601, 579, 612, 593, 357,  84, 374, 560, 599, 195,  38, 331, 273,
        266,  21, 369, 595, 134, 162, 245, 458, 332

In [ ]:
inicio_de_respostas = (
    'Boa pergunta!',
    'Deixe me ver, ',
    'Interessante questão, ',
    'Bom, ',
    'Então, ',
    'Ótima dúvida!',
    'Vamos lá, ',
    'Excelente pergunta!',
    'Certo, ',
    'Vamos analisar isso, '
)

In [ ]:
def responder(texto_usuario):
  resposta_chatbot = ''
  lista_sentencas_preprocessada.append(texto_usuario)

  tfidf = TfidfVectorizer()
  palavras_vetorizadas = tfidf.fit_transform(lista_sentencas_preprocessada)

  similaridade = cosine_similarity(palavras_vetorizadas[-1], palavras_vetorizadas)

  indice_sentenca = similaridade.argsort()[0][-2]
  vetor_similar = similaridade.flatten()
  vetor_similar.sort()
  vetor_encontrado = vetor_similar[-2]

  if (vetor_encontrado == 0):
    resposta_chatbot = '\nDesculpe, ainda não sei essa pergunta! Que tal uma nova pergunta de coração?'
    return resposta_chatbot
  else:
    resposta_chatbot = resposta_chatbot + lista_sentencas[indice_sentenca]
    return resposta_chatbot

### Passo 07: Ultilizar o HeartSalud

In [ ]:
import random  # Importando o módulo random

continuar = True
print('\n🫀Chatbot:\n')
print('Olá, sou o HeartSalud! gosto de falar sobre coração, me pergunte algo:\n ')
print('Use a documentação em caso de dificuldade\n ')
while continuar:
    texto_usuario = input()
    texto_usuario = texto_usuario.lower()

    if texto_usuario not in textos_despedidas_entrada:
        resposta_saudacao = responder_saudacao(texto_usuario)

        if resposta_saudacao is not None:
            print('---------------------------------------------------------------------------')
            print('\n🫀Chatbot:\n')
            print( resposta_saudacao + '\n')
            print('---------------------------------------------------------------------------')
        else:
            print('---------------------------------------------------------------------------')
            print('\n🫀Chatbot:\n')
            print(random.choice(inicio_de_respostas) + " " + responder(preprocessamento(texto_usuario)) + " " + '\n')
            print('---------------------------------------------------------------------------')
            lista_sentencas_preprocessada.remove(preprocessamento(texto_usuario))
    else:
      continuar = False
      despedida = random.choice(textos_despedidas_respostas)  # Corrigido de ramdom para random
      print('\n🫀Chatbot: ' + despedida)




🫀Chatbot:

Olá, sou o HeartSalud! gosto de falar sobre coração, me pergunte algo:
 
Use a documentação em caso de dificuldade
 
oi
---------------------------------------------------------------------------

🫀Chatbot:

pergunta ai sobre coração ❤️

---------------------------------------------------------------------------
Qual é o recorde de tempo de vida com um transplante de coração?
---------------------------------------------------------------------------

🫀Chatbot:

Vamos analisar isso,  o recorde de tempo de vida com um transplante de coração é 37 anos. 

---------------------------------------------------------------------------
Quem foi o primeiro cirurgião a realizar um transplante de coração e em que data isso ocorreu?
---------------------------------------------------------------------------

🫀Chatbot:

Vamos lá,  [87]

o primeiro transplante de coração bem sucedido foi realizado em 1967 pelo cirurgião sul-africano christiaan barnard. 

----------------------------------